### ISSUE TITLE
sendCmd - sleep 1?

### ISSUE THREAD

**Issue by catenamatteo** [patrickmarlier/powerspy.py#1]
Alciom protocol expects 1 second between each command sent to the wattmeter.
Shouldn't sendCmd() sleep 1 second at each call?

**Comment by patrickmarlier** [comment]
Extract from the PowerSpy protocol specification
"After each command sent to the PowerSpy the PC must wait for the answer or for a time-out value of 1s before sending any new command."
In our tool we wait for the answer up to 3 sec. See this:

```
DEFAULT_TIMEOUT = 3.0 # secs (float allowed, timeout to receive response from PowerSpy, except in realtime mode)
```

So maybe we can wait less than 3 sec but I am not sure it really matters.
