### ISSUE TITLE
Cannot identify the device

### ISSUE THREAD

**Issue by catenamatteo** [patrickmarlier/powerspy.py#2]
Sometimes,the wattmeter seems to crash between two realtime measurement runs. The provided error is "Cannot identify the device". Trying to relaunch the python script does not help.
In this case, it helps to forcibly stop previous acquisitions: 

``` python
[...]
  def init(self):
    if not self.checkID():
      logging.error("Cannot identify the device")
      self.rt_stop() 
      self.acquisition_stop() 
      self.close()  
      return False
[...]   
```

powerspy will "flush" the previous, dangling, acquisition and stop. python script has to be relaunched.

**Comment by patrickmarlier** [comment]
Can you run the tool in verbose mode and send all the output? (the -v option).
When you say "crash between two realtime measurement runs", you mean between two invocations of the powerspy.py tool, right? I would imagine here that the tool quit without stopping the realtime acquisition.
What is the command line that you use?

**Comment by catenamatteo** [comment]
Dear Patrick,

Yes, I'm talking about two invocations of powerspy.py. 
powerspy.py seems to terminate correctly, but the next invocation cannot identify the device (which is indeed busy, still doing the previous acquisition).
I would like to send you the output, but I'm not able to reproduce the bug. It appears randomly.
I'm using bash as command line.

**Comment by patrickmarlier** [comment]
Matteo,
If you can send the output (even if it is working correctly) for a full execution, it would help. Indeed, first we can check your powerspy version and also check if something else goes wrong.
BTW, did you press CTRL-C to stop the tool or did you set a duration?
Thanks a lot for reporting this.

**Comment by catenamatteo** [comment]
I'm simulating a CTRL-C by doing 

``` bash
    kill -s INT $PID
```

(this is because i'm monitoring the power consumption of another application, which has variable execution times. So I launch powerspy.py with the & operator, then I launch the application. The abovementioned line runs right after the application terminates)

**Comment by catenamatteo** [comment]
This is the the output for -v -i 0.1 -t 60
http://txt.do/6k1a

(but I usually run with -i 0.03)

**Comment by patrickmarlier** [comment]
Thanks a lot for the information. I would imagine this is due to a signal handling problem.
Just to be sure, did you check that $PID is the process id of powerspy.py and not the process id of your script? (I cannot figure out why the signal handler is not called here...)

**Comment by catenamatteo** [comment]
i'm doing this to launch and kill powerspy.py

``` bash
#!/bin/bash
launchPowerSpy() {

    PS2MAC=$1
    RATE=$2
    OUTPUT_FILE=$3
    powerspy.py -i $RATE $PS2MAC > $OUTPUT_FILE &
    PID=$!
    sleep 30
    #check if powerspy.py is running, otherwise retry
    if ps -p $PID > /dev/null
    then 
        echo $PID
    else
        echo $(launchPowerSpy $PS2MAC $RATE $OUTPUT_FILE)
    fi
}

killPowerSpy() {

    PID=$1
    kill -s INT $PID
    sleep 30
}
```

It usually works fine.
It is well possible that the bug is in my code. Anyway, problem is that powerspy2 remains unavailable and can't be reset to normal unless you unplug the device from the power socket. (Or, you force dangling acquisition to stop as I suggested)

**Comment by patrickmarlier** [comment]
maskur did a modification on exception handling and it may fix your problem. Could you give a try?

**Comment by catenamatteo** [comment]
Ok, I'll try the latest version and let you know if I get the same error

**Comment by catenamatteo** [comment]
Unluckily, I don't have the verbose output. But I have just got this error trying to terminate powerspy.py

```
Traceback (most recent call last):
  File "/home/matteo/powerspy.py/powerspy.py", line 435, in <module>
    dev.rt_capture(args.interval, args.time)
  File "/home/matteo/powerspy.py/powerspy.py", line 366, in rt_capture
    voltage, current, power, pvoltage, pcurrent = self.rt_read()
  File "/home/matteo/powerspy.py/powerspy.py", line 300, in rt_read
    hexa = values[i].decode("hex")
  File "/usr/lib/python2.7/encodings/hex_codec.py", line 42, in hex_decode
    output = binascii.a2b_hex(input)
TypeError: Odd-length string
```

Subsequent executions fail, returning:

```
ERROR:root:Cannot identify the device
```

**Comment by patrickmarlier** [comment]
Let's update a bit on this. Do you have still the original error (ie quit without closing properly the communication)? How frequently do you get the error about "TypeError: Odd-length string" ?

**Comment by catenamatteo** [comment]
I still see the problem, once and then. I cannot be more precise on the frequency of this issue

**Comment by patrickmarlier** [comment]
Can you be a bit more precise? Are you still seeing the problem "TypeError: Odd-length string" or a silent exit and then ("cannot identify the device")?

**Comment by catenamatteo** [comment]
"TypeError: Odd-length string". Then, if I try to connect to the device, I get "cannot identify..."

**Comment by patrickmarlier** [comment]
Thanks Matteo. This SIGINT (CTRL-C) in python is terrible... I propose to add a try/except/finally in rt_capture. Mascha: what do you think? Any better alternative here?

**Comment by patrickmarlier** [comment]
I have committed the change for try/except/finally. I hope it will finally solve your problem. Reopen the issue if it is not the case.
